### ISSUE TITLE
pyspiltcue CLI fails to handle filenames with '()' 

### ISSUE THREAD

**Issue by rosyth** [jeanslack/pysplitcue#2]
Same flac file with links to the two file names.
Modified cue files to point to the links correctly.

File with '(xyz)' fails due to something in pysplitcue.
If I copy the 'shnsplit' command, (with quoted flac file name) it works.

The variation without '(xyz)' works as expected.

`
$ pysplitcue -o flac -i 'Mytest (xyz).flac'
/bin/sh: 1: Syntax error: "(" unexpected
Process Error! Command 'shnsplit -o flac -f Mytest (xyz).cue -t "%n - %t" Mytest (xyz).flac' returned non-zero exit status 2.
$ pysplitcue -o flac -i 'Mytest.flac'
shnsplit: warning: discarding initial zero-valued split point
Splitting [Mytest.flac] (43:17.14) --> [01 - Track 01.flac] (8:01.49) : 100% OK
Splitting [Mytest.flac] (43:17.14) --> [02 - Track 02.flac] (3:11.41) : 100% OK
Splitting [Mytest.flac] (43:17.14) --> [03 - Track 03.flac] (4:44.51) : 100% OK
Splitting [Mytest.flac] (43:17.14) --> [04 - Track 04.flac] (1:43.38) : 100% OK
Splitting [Mytest.flac] (43:17.14) --> [05 - Track 05.flac] (4:49.45) : 100% OK
Splitting [Mytest.flac] (43:17.14) --> [06 - Track 06.flac] (5:33.18) : 100% OK
Splitting [Mytest.flac] (43:17.14) --> [07 - Track 07.flac] (3:54.45) : 100% OK
Splitting [Mytest.flac] (43:17.14) --> [08 - Track 08.flac] (2:55.58) : 100% OK
Splitting [Mytest.flac] (43:17.14) --> [09 - Track 09.flac] (2:29.64) : 100% OK
Splitting [Mytest.flac] (43:17.14) --> [10 - Track 10.flac] (5:52.55) : 100% OK
...done.

Apply tags on audio tracks...
`

**Comment by jeanslack** [comment]
Hello @rosyth 

Sorry, I haven't updated this little program for a long time. I just took a look at it and indeed the quotes are missing in the filenames.
Can you try it from the source code? 
If yes, download this archive: https://github.com/jeanslack/pysplitcue/archive/refs/heads/fix_filenames.zip
Let me know the result.

**Comment by rosyth** [comment]
The correction works, thanks.
```
$ pysplitcue -o flac -i 'Mytest (xyz).flac'
shnsplit: warning: discarding initial zero-valued split point
Splitting [Mytest (xyz).flac] (43:17.14) --> [01 - Track 01.flac] (8:01.49) : 100% OK
Splitting [Mytest (xyz).flac] (43:17.14) --> [02 - Track 02.flac] (3:11.41) : 100% OK
Splitting [Mytest (xyz).flac] (43:17.14) --> [03 - Track 03.flac] (4:44.51) : 100% OK
...
```

**Comment by rosyth** [comment]
I've tested your update, and it now works as expected, thanks.
Been busy most of today.
$ pysplitcue -o flac -i 'Mytest (xyz).flac'
shnsplit: warning: discarding initial zero-valued split point
Splitting [Mytest (xyz).flac] (43:17.14) --> [01 - Track 01.flac] (8:01.49)
: 100% OK
Splitting [Mytest (xyz).flac] (43:17.14) --> [02 - Track 02.flac] (3:11.41)
: 100% OK
Splitting [Mytest (xyz).flac] (43:17.14) --> [03 - Track 03.flac] (4:44.51)
: 100% OK
...
