### ISSUE TITLE
No executable after pip install

### ISSUE THREAD

**Issue by jej** [jeanslack/pysplitcue#6]
Thanks for this tool. Unfortunately, after the pip install I cannot launch pysplitcue. No executable script is found. Do I miss something?

Thx, J.

**Comment by jeanslack** [comment]
Hello @jej 

This is weird, I just tried installing it on Ubuntu 20.04 and Devuan 4.0 too and it works as expected for me.
Could you tell me how you installed pysplitcue and in which operating system please?

**Comment by jej** [comment]
Hi,
Just followed your command line. Tried a `pip install pysplitcue` (outside any venv). I use 21.10, python 3.9.
Hope it helps,
J.

**Comment by jeanslack** [comment]
Ok, I found the bug in the setup.py file. I'll fix it and release a new version soon. 
Thanks for reporting this.

**Comment by jej** [comment]
Cool thanks! It's a merry Merry Christmas :)
